services:
  - type: web
    name: chitraguess-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CLIENT_URL
        value: http://localhost:3000
